services:
    db:
        image: postgres:16
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
            POSTGRES_DB: appdb
        ports:
            - "5432:5432" # change left side to 5433 if 5432 is busy on host
        volumes:
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
